---
- hosts: all
  gather_facts: true
  tasks:
    - name: Check servers
      ping:

    - name: Debug ansible vars
      debug:
        var: ansible_facts
      when: DEBUG_FACTS == "true"

- hosts: setup_hosts
  become: true
  gather_facts: false
  roles:
    - prepare_hosts
  