---
- hosts: all
  gather_facts: true
  tasks:
    - name: Check servers
      ping:

    - name: Debug ansible vars
      debug:
        var: ansible_facts

- hosts: rpm_hosts
  become: true
  gather_facts: false
  roles:
    - prepare_hosts
  