---
- name: reboot_rpm_servers
  reboot:
    reboot_timeout: '180'
    test_command: hostname
  when: ansible_facts['os_family'] == "RedHat"

- name: reboot_apt_servers
  reboot:
    reboot_timeout: '180'
    test_command: hostname
  when: ansible_facts['os_family'] == "Debian"