---
- name: reboot_rpm_servers
  reboot:
    reboot_timeout: '180'
    test_command: hostname
  when: os_family == "RedHat"

- name: reboot_apt_servers
  reboot:
    reboot_timeout: '180'
    test_command: hostname
  when: os_family == "Debian"