---
- name: Set Hostnames
  hostname:
    name: "{{ HOSTNAME_PREFIX }}-{{ HOSTNAME_END }}"
  notify: 
    - reboot_apt_servers
    - reboot_rpm_servers
 
- name: Setup base packeges and full update RPM based systems
  block:

    - name: Add EPEL Release repository for RPM based hosts
      yum:
        name: epel-release
        state: present
  
    - name: Install base packages
      yum:
        name: ['vim', 'tree', 'htop', 'nc', 'mc', 'wget', 'curl', 'yum-utils', 'tc']
        state: present
        update_cache: yes

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
      notify: 
        - reboot_rpm_servers

  when: ansible_facts['os_family'] == "RedHat"

- name: Setup base packages and full update DEB based systems
  block:
    
    - name: Install based packages with update repositories caches
      apt:
        pkg: ['vim', 'tree', 'htop', 'nc', 'mc', 'wget', 'curl', 'tc', 'linux-cloud-tools']
        state: present
        update_cache: true

    - name: Update all packages
      apt:
        pkg: '*'
        state: latest
      notify: 
        - reboot_apt_servers

  when: ansible_facts['os_family'] == "Debian"

     