---
- name: Set Hostnames
  hostname:
    name: "{{ HOSTNAME_PREFIX }}-{{ HOSTNAME_END }}"
 
- name: Setup base packeges and full update RPM based systems
  block:

    - name: Add EPEL Release repository for RPM based hosts
      yum_repository:
        name: epel
        description: EPEL YUM REPO
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  
    - name: Install base packages
      yum:
        name: ['vim', 'tree', 'htop', 'nc', 'mc', 'wget', 'curl', 'yum-utils', 'tc']
        state: present

    - name: Update all packages
      yum:
        name: '*'
        state: latest
      notify: 
        - reboot_rpm_servers

  when: ansible_facts.os_family == "RedHat"

- name: Setup base packages and full update DEB based systems
  block:
    
    - name: Install based packages with update repositories caches
      apt:
        pkg: ['vim', 'tree', 'htop', 'nc', 'mc', 'wget', 'curl', 'tc', 'linux-cloud-tools']
        state: present
        update_cache: true

    - name: Update all packages
      apt:
        pkg: '*'
        state: latest
      notify: 
        - reboot_apt_servers

  when: ansible_facts.os_family == "Debian"

     